---
- name: Install Docker package
  ansible.builtin.apt:
    name:
      - docker.io
    state: present

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
